ASP .NET/Controllers/AdvertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using ASPMVC.Models;
using System.Globalization;
using Terradue.ServiceModel.Syndication;
using Microsoft.Owin.Host.SystemWeb;
using Microsoft.AspNet.Identity.Owin;
using System.IO;
using System.Web.Hosting;
using PagedList;
using System.Text;
using System.Xml;
using System.Threading.Tasks;

namespace ASPMVC.Controllers
{
    public class AdvertController : Controller
    {
        private IOurDbContext _ourdbcontext;

        public static List<ServiceViewModel> advList = new List<ServiceViewModel>();
        public static List<AllAdsViewModel> allAdsList = new List<AllAdsViewModel>();
        public static List<AllAdsViewModel> checkCatList = new List<AllAdsViewModel>();
        public static List<AllAdsViewModel> checkTagList = new List<AllAdsViewModel>();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AdvertController()
        {
            _ourdbcontext = new OurDbContext(new AdvDbContext());
        }

        public AdvertController(IOurDbContext ourdbcontext, ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _ourdbcontext = ourdbcontext;
            UserManager = userManager;
            SignInManager = signInManager;
        }


        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public class FeedResult : ActionResult
        {
            public Encoding ContentEncoding { get; set; }
            public string ContentType { get; set; }

            private readonly SyndicationFeedFormatter _feed;
            public SyndicationFeedFormatter Feed
            {
                get { return _feed; }
            }

            public FeedResult(SyndicationFeedFormatter feed)
            {
                _feed = feed;
            }

            public override void ExecuteResult(ControllerContext context)
            {
                if (context == null)
                    throw new ArgumentNullException("context");

                var response = context.HttpContext.Response;
                response.ContentType = !string.IsNullOrEmpty(ContentType) ? ContentType : "application/rss+xml";

                if (ContentEncoding != null)
                    response.ContentEncoding = ContentEncoding;

                if (_feed != null)
                    using (var xmlWriter = new XmlTextWriter(response.Output))
                    {
                        xmlWriter.Formatting = Formatting.Indented;
                        _feed.WriteTo(xmlWriter);
                    }
            }
        }


        #region Index

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            checkCatList.Clear();
            checkTagList.Clear();
            CreateCatAndTagList();


            Adverts(page, sortOrder, searchString, searchCategory, searchTag);
            return View();
        }

        #region Posts/AllPosts

        [ChildActionOnly]
        public ActionResult Adverts(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            advList.Clear();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;
            ViewBag.CurrentSearchCategory = searchCategory;
            ViewBag.CurrentSearchTag = searchTag;
            ViewBag.DateSortParm = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "title_desc" : "Title";


            var posts = _ourdbcontext.GetAds();
            foreach (var adv in posts)
            {
                var postCategories = GetAdvCategories(adv);
                var postTags = GetAdvTags(adv);
                var likes = _ourdbcontext.LikeDislikeCount("advlike", adv.Id);
                var dislikes = _ourdbcontext.LikeDislikeCount("advdislike", adv.Id);
                advList.Add(new ServiceViewModel() { Advert = adv, Modified = adv.Modified, Title = adv.Title, ShortDescription = adv.ShortDescription, PostedOn = adv.PostedOn, ID = adv.Id, AdvLikes = likes, AdvDislikes = dislikes, AdvCategories = postCategories, AdvTags = postTags, UrlSlug = adv.UrlSeo });
            }

            if (searchString != null)
            {
                advList = advList.Where(x => x.Title.ToLower().Contains(searchString.ToLower())).ToList();
            }

            if (searchCategory != null)
            {
                List<ServiceViewModel> newlist = new List<ServiceViewModel>();
                foreach (var catName in searchCategory)
                {
                    foreach (var item in advList)
                    {
                        if (item.AdvCategories.Where(x => x.Name == catName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkCatList)
                    {
                        if (item.Category.Name == catName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                advList = advList.Intersect(newlist).ToList();
            }

            if (searchTag != null)
            {
                List<ServiceViewModel> newlist = new List<ServiceViewModel>();
                foreach (var tagName in searchTag)
                {
                    foreach (var item in advList)
                    {
                        if (item.AdvTags.Where(x => x.Name == tagName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkTagList)
                    {
                        if (item.Tag.Name == tagName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                advList = advList.Intersect(newlist).ToList();
            }

            switch (sortOrder)
            {
                case "date_desc":
                    advList = advList.OrderByDescending(x => x.PostedOn).ToList();
                    break;
                case "Title":
                    advList = advList.OrderBy(x => x.Title).ToList();
                    break;
                case "title_desc":
                    advList = advList.OrderByDescending(x => x.Title).ToList();
                    break;
                default:
                    advList = advList.OrderBy(x => x.PostedOn).ToList();
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);

            return PartialView("Adverts", advList.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult AllAdverts(int? page, string sortOrder, string searchString, string[] searchCategory, string[] searchTag)
        {
            allAdsList.Clear();
            checkCatList.Clear();
            checkTagList.Clear();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearchString = searchString;
            ViewBag.CurrentSearchCategory = searchCategory;
            ViewBag.CurrentSearchTag = searchTag;
            ViewBag.DateSortParm = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "title_desc" : "Title";

            var posts = _ourdbcontext.GetAds();
            foreach (var adv in posts)
            {
                var postCategories = GetAdvCategories(adv);
                var postTags = GetAdvTags(adv);
                allAdsList.Add(new AllAdsViewModel() { AdvID = adv.Id, Date = adv.PostedOn, Description = adv.ShortDescription, Title = adv.Title, AdvCategories = postCategories, AdvTags = postTags, UrlSlug = adv.UrlSeo });
            }

            if (searchString != null)
            {
                allAdsList = allAdsList.Where(x => x.Title.ToLower().Contains(searchString.ToLower())).ToList();
            }

            CreateCatAndTagList();

            if (searchCategory != null)
            {
                List<AllAdsViewModel> newlist = new List<AllAdsViewModel>();
                foreach (var catName in searchCategory)
                {
                    foreach (var item in allAdsList)
                    {
                        if (item.AdvCategories.Where(x => x.Name == catName).Any())
                        {
                            newlist.Add(item);
                        }
                    }
                    foreach (var item in checkCatList)
                    {
                        if (item.Category.Name == catName)
                        {
                            item.Checked = true;
                        }
                    }
                }
                allAdsList = allAdsList.Intersect(newlist).ToList();
            }

            if (searchTag != null)
            {

ASP .NET/Views/Advert/AddCategoryToAdv.cshtml
@model ASPMVC.Models.AdvViewModel
@using ASPMVC.Models

@{
    ViewBag.Title = "AddCategoryToAdv";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("AddCategoryToAdv", "Advert", FormMethod.Post, new { @class = "addCatForm", role = "form" }))
{
    @Html.AntiForgeryToken()
    <table class="addCatCont">
        <tr>
            <td><a href="@Url.Action("AddNewCategory", "Advert", new { advid = Model.ID, callfrompost=true})" class="addremoveBtn" title="Add Category"><img src="@Url.Content("~/Content/images/post/add.png")" width="25" height="25" alt="add" /></a></td>
            <td><= Add New Category</td>
        </tr>
        <tr>
            <td></td>
            <td>
                @for (int i = 0; i < Model.Categories.Count(); i++)
                {
                    AdvDbContext db = new AdvDbContext();
                    string catId = Model.Categories[i].Id;
                    bool check = db.AdvCategories.Where(x => x.CatID == catId && x.AdvID == Model.ID).Select(x => x.Checked).FirstOrDefault();
                    if (check)
                    {
                        Model.Categories[i].Checked = true;
                        @Html.CheckBoxFor(m => m.Categories[i].Checked)
                    }
                    else
                    {
                        @Html.CheckBoxFor(m => m.Categories[i].Checked)
                    }

                    @Html.LabelFor(m => m.Categories[i].Checked, Model.Categories[i].Name)
                    @Html.HiddenFor(m => m.Categories[i].Id)<br />
                }
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.TextBoxFor(m => m.ID, new { type = "hidden" })
                <input class="addCatBtn" type="submit" value="&#x27a5;" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Main", "Index")
</div>

ASP .NET/Views/Advert/AddImageToAdv.cshtml
@model ASPMVC.Models.AdvViewModel

@{
    ViewBag.Title = "Add Video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddImageToAdv", "Advert", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="addVidCont">
        <input type="hidden" name="slug" value="@Model.UrlSeo" />
        <input type="hidden" name="advid" value="@Model.ID" />
        <input class="addVidToPost" type="url" name="Url" />
        <input class="addVidBtn" type="submit" value="&#x27a5;" />
    </div>
}

<div>
    @Html.ActionLink("Main", "Index")
</div>

ASP .NET/Views/Advert/AddNewAdv.cshtml
@model ASPMVC.Models.AdvViewModel
@{
    ViewBag.Title = "Add New Advert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddNewAdv", "Advert", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
<div class="form-style-2">
    <div class="form-style-2-heading">Create new advert</div>
    <form method="post">

        <label for="title">@Html.TextBoxFor(m => m.ID, new { @class = "editPostIdInp", @readonly = "readonly", style = "display: none;" })</label>
        <br>
        <label for="title">@Html.TextBoxFor(m => m.Author, new { @class = "editPostIdInp", @readonly = "readonly", style = "display: none;" })</label>
        <br>
        <label for="title">Title</label>@Html.TextBoxFor(m => m.Title, new { @class = "editPostTitleInp" })<br />
        <br>
        <label for="title">Meta</label>@Html.TextBoxFor(m => m.Meta, new { @class = "editPostMeta" })
        <br>
        <label for="title">UrlSeo</label>@Html.TextBoxFor(m => m.UrlSeo, new { @class = "editPostSeo" }) 
        <br>
       
        <label for="description"><h3>Short Description</h3></label>

       
        @Html.TextAreaFor(m => m.ShortDescription, new { @id = "editor1", Value = Model.ShortDescription })
        <script>
                            CKEDITOR.replace('editor1');
        </script>


        <label for="description"><h3>Description</h3></label>

        @Html.TextAreaFor(m => m.Body, new { @id = "editor2", Value = Model.Body })
        <script>
                            CKEDITOR.replace('editor2');
        </script>
        <br>

        <input class="comTextBtn" type="submit" value="&#x27a5;" />
    </form>
</div>
}

<div>
    @Html.ActionLink("Main", "Index")
</div>

ASP .NET/Views/Advert/AddNewCategory.cshtml
@model ASPMVC.Models.AdvViewModel

@{
    ViewBag.Title = "AddNewCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddNewCategory", "Advert", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <table class="newCatCont">
        <tr>
            <td>Name :</td>
            <td><input class="newCatInp" type="text" name="catName" /></td>
        </tr>
        <tr>
            <td>UrlSeo :</td>
            <td><input class="newCatInp" type="text" name="catUrlSeo" /></td>
        </tr>
        <tr>
            <td>Description :</td>
            <td><input class="newCatInp" type="text" name="catDesc" /></td>
        </tr>
        <tr>
            <td colspan="2">
                @if (Model != null)
                {
                    <input type="hidden" value="@Model.ID" name="advid" />
                }
                <input class="newCatBtn" type="submit" value="&#x27a5;" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP .NET/Views/Advert/Advert.cshtml
@model ASPMVC.Models.AdvViewModel
@using ASPMVC.Controllers
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = Model.Title;
    if (Model.PostTags != null)
    {
        ViewBag.Keywords = string.Join(" ", Model.PostTags.Select(t => t.Name).ToArray());
    }
    ViewBag.Description = Model.Meta;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
{
    <script src="~/Scripts/view.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
}

<div id="postScroll">
    <div class="postContainer">
        @if (User.IsInRole("Admin"))
        {
            <div class="postMenu">
                <div class="postMenuSub">
                    <a href="@Url.Action("EditAdvert","Advert",new {slug = Model.UrlSeo })" title="Edit"><img src="@Url.Content("~/Content/images/post/edit.png")" width="25" height="25" alt="edit" /></a>
                    <a href="@Url.Action("DeleteAdv","Advert",new {advid = Model.ID })" title="Delete"><img src="@Url.Content("~/Content/images/post/delete.png")" width="25" height="25" alt="delete" /></a>
                </div>
            </div>
        }
        else if (User.Identity.GetUserName() == Model.Author)
        {
            <div class="postMenu">
                <div class="postMenuSub">
                    <a href="@Url.Action("EditAdvertUser","Advert", new {slug = Model.UrlSeo })" title="Edit"><img src="@Url.Content("~/Content/images/post/edit.png")" width="25" height="25" alt="edit" /></a>
                </div>
            </div>
        }
        <div class=" postHeader">
            @if (Model.ID != Model.FirstAdvId)
            {
                
                @Html.ActionLink("<< Previous", "Advert", "Advert", new { slug = Model.PreviousAdvSlug, sortorder = ViewBag.CurrentSort }, new { style = "float:left;", id = "previous" })
                
            }
            @if (Model.ID != Model.LastAdvId)
            {
                @Html.ActionLink("Next >>", "Advert", "Advert", new { slug = Model.NextAdvSlug, sortorder = ViewBag.CurrentSort }, new { style = "float:right;", id = "next" })
            }

        </div>

        <div class="postTitle"><h2>@Model.Title</h2></div>
        <div class="addthis_sharing_toolbox"></div>
        <div class="postVote" id="postVote">
            <table>
                <tr><td style="text-align:center; color:green; font-style:italic;">@Model.AdvLikes</td></tr>
                <tr><td><a href="@Url.Action("UpdateAdvLike", "Advert", new { slug=Model.UrlSeo, advid = Model.ID,username = User.Identity.GetUserName(), likeordislike = "like",sortorder = ViewBag.CurrentSort })"><img src="@Url.Content("~/Content/images/post/upvote.png")" width="30" height="30" alt="upvote" /></a></td></tr>
                <tr><td><a href="@Url.Action("UpdateAdvLike", "Advert", new { slug=Model.UrlSeo, advid = Model.ID,username = User.Identity.GetUserName(), likeordislike = "dislike" ,sortorder = ViewBag.CurrentSort})"><img src="@Url.Content("~/Content/images/post/downvote.png")" width="30" height="30" alt="downvote" /></a></td></tr>
                <tr><td style="text-align:center; color:#b50000; font-style:italic;">@Model.AdvDislikes</td></tr>
            </table>
        </div>
        
        @if (Model.Images != null)
        {
            foreach (var video in Model.Images)
            {
                <div class="advImage">
                    <img width="560" height="400" src="@video.ImageUrl" frameborder="0" overflow="hidden" allowfullscreen>
                </div>
            }
        }

        @{
            AdvertController advCtrl = new AdvertController();
        }
        <div class="postBody">@Html.Raw(Model.Body)</div>
        <div class="advAuthor">Author: @Html.Raw(Model.Author)</div>
    </div>
    @{Html.RenderPartial("Comments", Model.CommentViewModel);}
</div>

<div>
    @Html.ActionLink("Main", "Index")
</div>

ASP .NET/Views/Advert/Adverts.cshtml
@model PagedList.IPagedList<ASPMVC.Models.ServiceViewModel>
@using PagedList.Mvc;
@using ASPMVC.Controllers
<link href="~/Content/css/PagedList.css" rel="stylesheet" />


@{
    AdvertController advCtrl = new AdvertController();
    int advnum = 0;
}

<div style="overflow:hidden;width:100%;">
    <table style="float:right;">
        <tr>
            <th>Sort by :</th>
            <th>
                @using (Html.BeginForm("Index", "Advert", FormMethod.Get))
                {
                if (ViewBag.CurrentSearchCategory != null)
                {
                    foreach (var item in ViewBag.CurrentSearchCategory)
                    {
                            <input type="hidden" name="searchCategory" value="@item" />
                        }
                    }
                    if (ViewBag.CurrentSearchTag != null)
                    {
                        foreach (var item in ViewBag.CurrentSearchTag)
                        {
                            <input type="hidden" name="searchTag" value="@item" />
                        }
                    }
                    <input type="hidden" name="searchString" value="@ViewBag.CurrentSearchString" />
                    <input type="hidden" name="sortOrder" value="@ViewBag.DateSortParm" />
                    <input class="submitBtnLink" type="submit" value="Date" />
                }
            </th>
            <th class="tableTitle">
                @using (Html.BeginForm("Index", "Advert", FormMethod.Get))
            {
                if (ViewBag.CurrentSearchCategory != null)
                {
                    foreach (var item in ViewBag.CurrentSearchCategory)
                    {
                            <input type="hidden" name="searchCategory" value="@item" />
                        }
                    }
                    if (ViewBag.CurrentSearchTag != null)
                    {
                        foreach (var item in ViewBag.CurrentSearchTag)
                        {
                            <input type="hidden" name="searchTag" value="@item" />
                        }
                    }
                    <input type="hidden" name="searchString" value="@ViewBag.CurrentSearchString" />
                    <input type="hidden" name="sortOrder" value="@ViewBag.TitleSortParm" />
                    <input class="submitBtnLink" type="submit" value="Title" />
                }
            </th>
        </tr>
    </table>
</div>



@foreach (var adv in Model)
{
    advnum++;
    var total = adv.AdvLikes - adv.AdvDislikes;
    <div class="postDescContainer">

        <div class="postPubDate">
            <div>@adv.PostedOn.ToShortDateString()</div>
        </div>
        <a href="#">
            <div class="postDescTitle"><h3>@Html.ActionLink(@adv.Title, "Advert", "Advert", new { slug = @adv.UrlSlug }, null)</h3></div>
        </a>
        <div class="postDescCategory">
            <label>Category:&nbsp;</label>
            @{
                var advCats = advCtrl.GetAdvCategories(adv.Advert);
                int advcatnum = 0;
                foreach (var cat in advCats)
                {
                    advcatnum++;
                    <a href="#">
                        <div class="postDescCatNames">
                            @cat.Name@if (advcatnum < advCats.Count())
                            {
                                @Html.Raw(",&nbsp;")
                            }
                        </div>
                    </a>
                }
            }
        </div>
        <div class="postDescBody">
            @{
                var advImage = advCtrl.GetAdvImage(adv.Advert);
                if (advImage != null)
                {
                    <div class="postVidCont">
                        @foreach (var content in advImage)
                        {
                            <a href="@content.ImageUrl" class="postVidThumb" target="_blank"><img src="@Url.Content(content.Imagehumbnail)" width="200" height="200" /></a>
                        }
                    </div>
                }
            }
            @Html.Raw(adv.ShortDescription)
            @Html.ActionLink("Read More...", "Advert", "Advert", new {slug = adv.UrlSlug }, null)
        </div>
        @if (total >= 0)
        {
            <table class="postLikes">
                <tr>
                    <td style="text-align:center; color:green; font-style:italic;">@total</td>
                    <td><img src="@Url.Content("~/Content/images/post/like.png")" width="20" height="20" alt="upvote" /></td>
                </tr>
            </table>
        }
        else
        {
            <table class="postDislikes">
                <tr>
                    <td style="text-align:center; color:#b50000; font-style:oblique;">@total</td>
                    <td><img src="@Url.Content("~/Content/images/post/dislike.png")" width="20" height="20" alt="downvote" /></td>
                </tr>
            </table>
        }
    </div>
}

<div id="spacer"></div>
<div class="paging">
    <div class="pagenum">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    </div>
    @{
        List<string> searchCatList = new List<string>();
        List<string> searchTagList = new List<string>();
        if (ViewBag.CurrentSearchCategory != null)
        {
            foreach (var item in ViewBag.CurrentSearchCategory)
            {
                searchCatList.Add(item);
            }
        }
        if (ViewBag.CurrentSearchTag != null)
        {
            foreach (var item in ViewBag.CurrentSearchTag)
            {
                searchTagList.Add(item);
            }
        }
    }
    @if (ViewBag.CurrentSearchCategory != null || ViewBag.CurrentSearchTag != null)
    {
        @Html.PagedListPager(Model, page => Url.Action("Index", "Advert", new { page, sortOrder = ViewBag.CurrentSort, searchString = ViewBag.SearchString }) + "?" + string.Join("&", searchCatList.Select(x => "searchCategory=" + x)) + "&" + string.Join("&", searchTagList.Select(x => "searchTag=" + x)))
    }
    else
    {
        @Html.PagedListPager(Model, page => Url.Action("Index", "Advert", new { page, sortOrder = ViewBag.CurrentSort, searchString = ViewBag.SearchString }))
    }
</div>

ASP .NET/Views/Advert/CategoriesAndTags.cshtml
@using ASPMVC.Controllers
@{
    ViewBag.Title = "Categories And Tags";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var categories = AdvertController.checkCatList;
    var tags = AdvertController.checkTagList;
}

@using (Html.BeginForm("RemoveCatAndTag", "Advert", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <table class="catsAndTags">
        <tr>
            <th>Categories</th>
            @*<th>Tags</th>*@
        </tr>
        <tr>
            <td><a href="@Url.Action("AddNewCategory", "Advert", new { callfrompost = false })" class="addremoveBtn" title="Add Category"><img src="@Url.Content("~/Content/images/post/add.png")" width="25" height="25" alt="add" style="float:left;" /><div style="float:left;margin-left:5px;">New Category</div></a></td>
            @*<td><a href="@Url.Action("AddNewTag", "Advert", new { callfrompost = false })" class="addremoveBtn" title="Add Tag"><img src="@Url.Content("~/Content/images/post/add.png")" width="25" height="25" alt="add" style="float:left;" /><div style="float:left;margin-left:5px;">New Tag</div></a></td>*@
        </tr>
        <tr>
            <td>
                @foreach (var cat in categories)
                {
                    <div>
                        <input type="checkbox" name="categoryNames" value="@cat.Category.Name" /> @cat.Category.Name
                    </div>
                }
            </td>
            @*<td>
                @foreach (var tag in tags)
                {
                    <div>
                        <input type="checkbox" name="tagNames" value="@tag.Tag.Name" /> @tag.Tag.Name
                    </div>
                }
            </td>*@
        </tr>
        <tr>
            <td colspan="2">
                <input class="indexFiltBtn" type="submit" value="Remove" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP .NET/Views/Advert/EditComment.cshtml
@model ASPMVC.Models.CommentViewModel

@{
    ViewBag.Title = "EditComment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="newComment">
    @using (Html.BeginForm("EditComment", "Advert", FormMethod.Post, new { @class = "comTextdivParent", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="editComment">
            <textarea name="commentBody" id="editComment">@Model.Body</textarea>
            <script>
                CKEDITOR.replace('editComment',
                    {
                        customConfig: '/Scripts/ckEditorConfig1.js'
                    });
            </script>
        </div>
        <div class="comTextSub">
            <input name="commentid" value="@Model.Id" type="hidden" />
            <input class="comTextBtn" type="submit" value="&#x27a5;" />
        </div>

    }
</div>

ASP .NET/Views/Advert/EditReply.cshtml
@model ASPMVC.Models.CommentViewModel

@{
    ViewBag.Title = "EditReply";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="newComment">
    @using (Html.BeginForm("EditReply", "Advert", FormMethod.Post, new { @class = "comTextdivParent", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="editReply">
            <textarea name="replyBody" id="editComment">@Model.Body</textarea>
            <script>
                CKEDITOR.replace('editComment',
                    {
                        customConfig: '/Scripts/ckEditorConfig1.js'
                    });
            </script>
        </div>
            <div class="comTextSub">
                <input name="replyid" value="@Model.Id" type="hidden" />
                <input class="comTextBtn" type="submit" value="&#x27a5;" />
            </div>

            }
        </div>